# Site settings
title:       Nate Willard Engineering
email:       nate.a.willard@gmail.com
author:      Nate Willard
description: "Works in progress eternal"
baseurl:     "/blog"
url:         "http://www.natewillard.com"
date_format: "%b %-d, %Y"

# Google services
google_analytics: UA-66886333-1
google_verification:

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false
show_social_icons:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
github_username: RandomSeeded
bitbucket_username:
stackoverflow_id: 3062972
twitter_username:
google_plus_id:
linkedin_username: natewillard
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  compressed: true
